### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by stephen-TT** [the0807/YOLOv8-ONNX-TensorRT#1]
为啥这个仓库里没看到分配现存，设定输入输出这些步骤，和别人的tensorrt加速的流程好像不一样呀？

**Comment by the0807** [comment]
These codes are based on the documentation from ultralytics. I created TensorRT using the functions provided by ultralytics, you can see more details in the documentation for YOLOv8.

**Comment by stephen-TT** [comment]
> These codes are based on the documentation from ultralytics. I created TensorRT using the functions provided by ultralytics, you can see more details in the documentation for YOLOv8.

Roger that, thanks!
