### ISSUE TITLE
calibration_data.cache

### ISSUE THREAD

**Issue by Egorundel** [the0807/YOLOv8-ONNX-TensorRT#2]
Will your method help to create a `calib.cache` if I have an ONNX model with a dynamic batch size and I have an NMS module at the output of the model?

input:
![Screenshot from 2024-07-30 13-22-57](https://github.com/user-attachments/assets/64bd7546-3f87-483c-996c-94017b574805)

output:
![Screenshot from 2024-07-30 13-23-07](https://github.com/user-attachments/assets/8622b177-adc3-4e93-81bc-282714097800)

**Comment by the0807** [comment]
When exported to int8, it automatically collaborate and creates calib.cache

**Comment by Egorundel** [comment]
@the0807 In fact, calibration does not care whether there is a dynamic batch size or not and whether there is an NMS module or not?

**Comment by the0807** [comment]
@Egorundel I don't know the details. However, Nvidia's TensorRT documentation may be helpful.
